### ISSUE TITLE
unsupported_legacy_plugin

### ISSUE THREAD

**Issue by dotmilk** [senecajs-labs/seneca-dynamo-store#2]
# Seneca Fatal Error

Message: seneca: The plugin seneca-dynamodb uses an unsupported legacy callback to indicate plugin definition is complete: function (si, opts, cb) { ... }. The correct format is: function(options) { ... }. For more details, please see http://senecajs.org/write-a-plugin.html

Code: unsupported_legacy_plugin

**Comment by darsee** [comment]
Looks like I need to update to support the latest version of seneca. I will hopefully get around to this sometime next week. In the meantime, pull requests welcome!

**Comment by dotmilk** [comment]
Well, apparently i was pulling from the wrong npm package? cause i re-installed and that error is now gone, it looks like.

but it seems like there is a new error. I'm new to seneca, or i would totally fix the problem, but as far as i can tell your initialising code looks just like the mysql data entity one that works. 

But now that i have it working there is a new error. Which i will open in a second.

**Comment by dotmilk** [comment]
https://www.npmjs.com/package/seneca-dynamodb

points to the error generating code.

Where as this 

https://www.npmjs.com/package/seneca-dynamo-store

points to working code aside from #3

**Comment by darsee** [comment]
I've added a deprecation warning to [seneca-dynamodb](https://www.npmjs.com/package/seneca-dynamodb).
